Repository jenkins-infra/pipeline-metadata-utils, pull requests merged in 2022-07, with the labels that each got.

#9 Fix: Javadoc errors
  Jenkinsfile
  src/main/java/hudson/MockJenkins.java
  src/main/java/org/jenkinsci/infra/tools/HyperLocalPluginManager.java
Labels: bug

#10 Enable Gitpod
  .gitpod.Dockerfile
  .gitpod.yml
Labels: enhancement

#16 Improved repo's automation tooling
  .github/dependabot.yml
  .github/release-drafter.yml
  .github/workflows/jenkins-security-scans.yml
  .github/workflows/release-drafter.yml
Labels: chore
